server:
  port: 8082
spring:
  application:
    name: urotaxi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://urotaximysqldb/urotaxidb
    username: root
    password: welcome1
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
  mvc:
    view:
      suffix: .html
management:
  endpoint:
    health:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - health